### ISSUE TITLE
是否有计划支持python 3.7？

### ISSUE THREAD

**Issue by plyxyz** [HuberTRoy/MusicBox#22]
在python3.7运行时，
Traceback (most recent call last):
  File "/usr/local/bin/musicplayer", line 7, in <module>
    from MusicPlayer.music import start
  File "/usr/local/lib/python3.7/site-packages/MusicPlayer/music.py", line 33, in <module>
    from quamash import QEventLoop
  File "/usr/local/lib/python3.7/site-packages/quamash/__init__.py", line 275
    future = asyncio.async(future, loop=self)
                         ^
SyntaxError: invalid syntax

看起来应该是python3.7的async接口改了所以不兼容的。

 - OS: [osx-python3.7]

**Comment by HuberTRoy** [comment]
3.7 计划 7月发布第一个维护版本（3.7.1），但目前还未发布。
另外`Mac` 下应该无法运行。#16

**Comment by plyxyz** [comment]
mac下运行没问题啊。虽然有的地方界面有点异常(上面看到一排空白按键)。
呃，如果是eye3d的问题，mac下这个库是eyeD3。现在版本0.8.7了。你代码里要求0.8.0我就装了个0.8.0的就正常了……
pip3 install --upgrade eyeD3==0.8.0
