### ISSUE TITLE
ImportError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by impce-lg** [HuberTRoy/MusicBox#33]
sudo musicplayer 
Traceback (most recent call last):
  File "/usr/local/bin/musicplayer", line 11, in <module>
    load_entry_point('Music-Player==1.0.5.1', 'console_scripts', 'musicplayer')()
  File "/home/huanhexiao/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/huanhexiao/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/huanhexiao/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/huanhexiao/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/Music_Player-1.0.5.1-py3.5.egg/MusicPlayer/music.py", line 33, in <module>
    from quamash import QEventLoop
  File "/usr/local/lib/python3.5/dist-packages/Quamash-0.6.1-py3.5.egg/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'PyQt5.sip'

**Comment by HectorHe** [comment]
这个问题解决了吗？我也遇到了，怎么解决的？

**Comment by HuberTRoy** [comment]
@HectorHe 
重装`PyQt5`，windows下可找exe安装。
