### ISSUE TITLE
运行时出现错误求解

### ISSUE THREAD

**Issue by Cznorth** [HuberTRoy/MusicBox#36]
Traceback (most recent call last):
  File "/usr/local/bin/musicplayer", line 11, in <module>
    load_entry_point('Music-Player==1.0.5.1', 'console_scripts', 'musicplayer')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/Music_Player-1.0.5.1-py3.6.egg/MusicPlayer/music.py", line 33, in <module>
    from quamash import QEventLoop
  File "/usr/local/lib/python3.6/dist-packages/Quamash-0.6.1-py3.6.egg/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'PyQt5.sip'

求解

**Comment by HuberTRoy** [comment]
@ChenHackerGit 
尝试重新安装PyQt5。

**Comment by gameboyring** [comment]
同样的问题,系统是win7,无解
