### ISSUE TITLE
点击播放就退出? Error: '' fish: 'python3 music.py' terminated by signal SIGABRT (Abort)

### ISSUE THREAD

**Issue by biluohc** [HuberTRoy/MusicBox#6]
```sh
(py3v)  b/MusicPlayer/MusicPlayer ╍ python3 music.py 

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:3218:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:6378:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:6388:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:6438:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:6551:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(python3:26993): Gtk-WARNING **: Theme parsing error: gtk.css:6574:52: The :prelight pseudo-class is deprecated. Use :hover instead.
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
读取或保存cookies出错 ['cookies/playlist/musicList.cks']
读取或保存cookies出错 ['cookies/mediaPlaylist/musics.cks', 'cookies/mediaPlaylist/mediaList.cks']
读取或保存cookies出错 ['cookies/headers/loginInfor.cks']
Traceback (most recent call last):
  File "/home/mxo/bin/MusicPlayer/MusicPlayer/widgets/player.py", line 925, in dealError
    musicInfo = self.playList.mediaList.pop(self.currentMedia().canonicalUrl().toString())
KeyError: ''
fish: 'python3 music.py' terminated by signal SIGABRT (Abort)
```
这个不是依赖没装吧? 另外Linux下不能全屏?

**Comment by HuberTRoy** [comment]
@biluohc 
可以知道下具体的情况吗。
看样子是播放列表里存在一个没有播放地址的音乐信息。
不过不知道这种情况是如何发生的。

全屏目前没做，不过Linux下应该可以随意拉伸。这个加入TODO。

**Comment by biluohc** [comment]
libQt5Multimedia5-5.6.2-1.4.x86_64

虚拟环境里的python3.6, 发行版信息如下
```
(py3v)  D/cache screenfetch -n
 mxo@Tum
 OS: openSUSE 42.3
 Kernel: x86_64 Linux 4.4.87-25-default
 Uptime: 3h 55m
 Packages: 2371
 Shell: fish 2.6.0
 Resolution: 1920x1080
 DE: GNOME 3.20.2
 WM: GNOME Shell
 WM Theme: Adwaita
 GTK Theme: Paper [GTK2/3]
 Icon Theme: Numix-Circle-Light
 Font: ???? 15
 CPU: Intel Core i7-4710MQ CPU @ 8x 3.5GHz
 RAM: 3533MiB / 7894MiB
```

**Comment by biluohc** [comment]
你使用了什么log不, 否则具体的要手动打印变量?
```python
    def dealError(self, error):
        # 具体内容看文档:
        # http://doc.qt.io/qt-5/qmediaplayer.html
        if error:
            print(self.playList.mediaList)
            print("\'", self.currentMedia().canonicalUrl().toString(),"\'" )
            musicInfo = self.playList.mediaList.pop(self.currentMedia().canonicalUrl().toString())
            self.loadRealMusicUrl(musicInfo)
```

```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
读取或保存cookies出错 ['cookies/playlist/musicList.cks']
读取或保存cookies出错 ['cookies/mediaPlaylist/musics.cks', 'cookies/mediaPlaylist/mediaList.cks']
读取或保存cookies出错 ['cookies/headers/loginInfor.cks']
{'http(0, 28568227)': {'url': 'http(0, 28568227)', 'name': '花枝春野', 'time': '03:49', 'author': '不才', 'music_img': 'http://p1.music.126.net/D22IKBn-eUq-EebVSbAuJA==/5934064255276851.jpg', 'music_id': 28568227, 'lyric': None}}
'  '
Traceback (most recent call last):
  File "/home/mxo/bin/MusicPlayer/MusicPlayer/widgets/player.py", line 927, in dealError
    musicInfo = self.playList.mediaList.pop(self.currentMedia().canonicalUrl().toString())
KeyError: ''
fish: 'python3 music.py' terminated by signal SIGABRT (Abort
```

**Comment by HuberTRoy** [comment]
@biluohc 
目前并没有使用log。

貌似是QMediaPlayer在Linux下有些问题。使用的解码器是GStreamer是吗。

**Comment by biluohc** [comment]
应该是GStreamer

**Comment by HuberTRoy** [comment]
@biluohc 
如果虾米和QQ音乐也不能播放，之后会尝试换一种方式实现播放音乐。

**Comment by biluohc** [comment]
也不行, 先虾米后qq
```
(py3v)  b/MusicPlayer/MusicPlayer ╍ python3 music.py 

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:3218:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:6378:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:6388:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:6438:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:6551:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(python3:12874): Gtk-WARNING **: Theme parsing error: gtk.css:6574:52: The :prelight pseudo-class is deprecated. Use :hover instead.
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
读取或保存cookies出错 ['cookies/playlist/musicList.cks']
读取或保存cookies出错 ['cookies/mediaPlaylist/musics.cks', 'cookies/mediaPlaylist/mediaList.cks']
读取或保存cookies出错 ['cookies/headers/loginInfor.cks']
{'http://m128.xiami.net/247/13247/105250/1333147_3530417_l.mp3?auth_key=1508641200-0-0-8a1610a2a865dcc800a01b04d6a251bc': {'url': 'http://m128.xiami.net/247/13247/105250/1333147_3530417_l.mp3?auth_key=1508641200-0-0-8a1610a2a865dcc800a01b04d6a251bc', 'name': 'Better Man', 'time': '03:22', 'author': 'Robbie Williams', 'music_img': 'http://pic.xiami.net/images/album/img47/13247/1052501393388654_1.jpg', 'music_id': 1333147, 'lyric': 'http://img.xiami.net/lyric/47/1333147_1469515613_1030.xtrc'}}
'  '
Traceback (most recent call last):
  File "/home/mxo/bin/MusicPlayer/MusicPlayer/widgets/player.py", line 927, in dealError
    musicInfo = self.playList.mediaList.pop(self.currentMedia().canonicalUrl().toString())
KeyError: ''
fish: 'python3 music.py' terminated by signal SIGABRT (Abort)
(py3v)  b/MusicPlayer/MusicPlayer ╍ python3 music.py                                                                                         (134) (6s 475ms) 

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:3218:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:6378:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:6388:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:6438:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:6551:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(python3:13107): Gtk-WARNING **: Theme parsing error: gtk.css:6574:52: The :prelight pseudo-class is deprecated. Use :hover instead.
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
读取或保存cookies出错 ['cookies/playlist/musicList.cks']
读取或保存cookies出错 ['cookies/mediaPlaylist/musics.cks', 'cookies/mediaPlaylist/mediaList.cks']
读取或保存cookies出错 ['cookies/headers/loginInfor.cks']
{'http://111.7.162.145/streamoc.music.tc.qq.com/C400001QiCnX3cvPB3.m4a?vkey=BD6A5FF34340AAB10464021707929D20F6138FF723467038997117E9F90719EB90D45AFC961E0E7B8DFAAC4AD940A15F203A3530CAC9D19B&guid=3768717388': {'url': 'http://111.7.162.145/streamoc.music.tc.qq.com/C400001QiCnX3cvPB3.m4a?vkey=BD6A5FF34340AAB10464021707929D20F6138FF723467038997117E9F90719EB90D45AFC961E0E7B8DFAAC4AD940A15F203A3530CAC9D19B&guid=3768717388', 'name': 'Walking On The Sidewalk', 'time': '02:28', 'author': 'Lullatone', 'music_img': 'https://y.gtimg.cn/music/photo_new/T002R300x300M000003lI6Vu3XzrMF.jpg', 'music_id': 7154890, 'lyric': 'qq'}}
'  '
Traceback (most recent call last):
  File "/home/mxo/bin/MusicPlayer/MusicPlayer/widgets/player.py", line 927, in dealError
    musicInfo = self.playList.mediaList.pop(self.currentMedia().canonicalUrl().toString())
KeyError: ''
fish: 'python3 music.py' terminated by signal SIGABRT (Abort)
(py3v)  b/MusicPlayer/MusicPlayer ╍                                                                                                                (8s 177ms) 
```

**Comment by HuberTRoy** [comment]
@biluohc 
```
pyqt5.qtmultimedia
libqt5multimedia5-plugins
```
这两个应该安装了吧。
不应该出现key是空的情况呀。
我在Ubuntu的虚拟环境下是正常的。

**Comment by biluohc** [comment]
opensuse没有这个`-plugins`(-i是已经安装了的), ,pyqt5的话, pip虚拟环境里,`pip install -r requirements.txt`应该已经装了.

```
i+ | GStreamer Multimedia Codecs               | Multimedia playback for APE, AVI, FLAC, FLX, Flash, MKV, MP4, Speex, VP8, VP9 and WAV | 应用程序
i+ | libQt5Multimedia5                         | Qt 5 Multimedia Library                                                               | 软件包  
   | libQt5Multimedia5-32bit                   | Qt 5 Multimedia Library                                                               | 软件包  
   | libQt5Multimedia5-debuginfo               | Debug information for package libQt5Multimedia5                                       | 软件包  
   | libQt5Multimedia5-debuginfo-32bit         | Debug information for package libQt5Multimedia5                                       | 软件包  
   | libqt5-qtmultimedia                       | Qt 5 Multimedia Library                                                               | 源代码包
   | libqt5-qtmultimedia-debugsource           | Debug sources for package libqt5-qtmultimedia                                         | 软件包  
i+ | libqt5-qtmultimedia-devel                 | Qt Development Kit                                                                    | 软件包  
   | libqt5-qtmultimedia-devel-32bit           | Qt Development Kit                                                                    | 软件包  
   | libqt5-qtmultimedia-examples              | Qt5 multimedia examples                                                               | 软件包  
   | libqt5-qtmultimedia-examples-debuginfo    | Debug information for package libqt5-qtmultimedia-examples                            | 软件包  
   | libqt5-qtmultimedia-private-headers-devel | Non-ABI stable experimental API                                                       | 软件包  
i  | multimedia                                | 多媒体                                                                                | 软件集  
i  | patterns-openSUSE-gnome_multimedia        | GNOME 多媒体                                                                          | 软件包  
i  | patterns-openSUSE-gnome_multimedia_opt    | GNOME 多媒体                                                                          | 软件包  
   | patterns-openSUSE-kde_multimedia          | KDE 多媒体                                                                            | 软件包  
i  | patterns-openSUSE-multimedia              | 多媒体                                                                                | 软件包  
i  | patterns-openSUSE-multimedia_opt          | 多媒体                                                                                | 软件包  

```

**Comment by HuberTRoy** [comment]
@biluohc 
之后会尝试换一种方式实现播放音乐。

**Comment by biluohc** [comment]
请问有几种方法啊？

**Comment by biluohc** [comment]
哪几种?

**Comment by HuberTRoy** [comment]
@biluohc 
待探索，目前不清楚。

**Comment by HuberTRoy** [comment]
@biluohc 
已添加最大化。

**Comment by biluohc** [comment]
辛苦了.

**Comment by Tecyang** [comment]
这个问题应该还在，我今天下载下来代码调试也是这样，太迟了先睡了

**Comment by HuberTRoy** [comment]
@Tecyang 
这个Issue还没解决，目前还是使用Qt的播放系统。
